spring:
  application:
    name: basic-services-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lgmn-mysql:53306/lgmn_basic_services?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9090
management:
  port: 9091
dubbo:
  registry:
    id: basic-services-provider-registry
    address: nacos://nacos-standalone-mysql:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  application:
    id: basic-services-provider
    name: basic-services-provider
  scan:
    basePackages: com.lgmn.basicservices.provider.service
demo:
  service:
    version: 1.0.0
nacos:
  config:
    server-addr: nacos-standalone-mysql:8848
