nacos:
  config:
    server-addr: 127.0.0.1:8848
demo:
  service:
    version: 1.0.0
spring:
  application:
    name: basic-services-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lgmn_basic_services?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
      use_sql_comments: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
dubbo:
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    id: basic-services-provider-registry
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.lgmn.basicservices.provider.service
  application:
    id: basic-services-provider
    name: basic-services-provider